# Generated by Django 4.0.3 on 2022-03-13 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extract',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Today's date(dd/mm/yyyy)"),
        ),
    ]
