# Generated by Django 4.0.3 on 2022-03-13 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleapp', '0002_alter_extract_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name="Today's date")),
                ('Sales_person', models.CharField(choices=[('anna', 'Anna'), ('bob', 'Bob'), ('charlene', 'Charlene'), ('david', 'David')], max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_country', models.CharField(choices=[('united kingdom', 'United Kingdom'), ('france', 'France'), ('germany', 'Germany'), ('netherlands', 'Netherlands'), ('spain', 'Spain')], max_length=100)),
                ('Desired_fruit', models.CharField(choices=[('apples', 'Apples'), ('pears', 'Pears'), ('strawberries', 'Strawberries'), ('bananas', 'Bananas')], max_length=100)),
            ],
        ),
    ]
