# Generated by Django 4.0.3 on 2022-03-13 02:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('saleapp', '0003_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extract',
            name='Customer_name',
        ),
        migrations.AddField(
            model_name='extract',
            name='Desired_fruit',
            field=models.CharField(choices=[('apples', 'Apples'), ('pears', 'Pears'), ('strawberries', 'Strawberries'), ('bananas', 'Bananas')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extract',
            name='Sales_person',
            field=models.CharField(choices=[('anna', 'Anna'), ('bob', 'Bob'), ('charlene', 'Charlene'), ('david', 'David')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extract',
            name='customer_country',
            field=models.CharField(choices=[('united kingdom', 'United Kingdom'), ('france', 'France'), ('germany', 'Germany'), ('netherlands', 'Netherlands'), ('spain', 'Spain')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extract',
            name='customer_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
