# Generated by Django 4.0.3 on 2022-03-13 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleapp', '0004_remove_extract_customer_name_extract_desired_fruit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extract',
            old_name='customer_name',
            new_name='Customer_name',
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Today's date(dd/mm/yyyy)"),
        ),
    ]
