# Generated by Django 4.0.3 on 2022-03-13 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saleapp', '0005_rename_customer_name_extract_customer_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
