# Generated by Django 4.0.3 on 2022-03-13 10:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('saleapp', '0006_delete_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extract',
            name='date',
        ),
        migrations.AddField(
            model_name='extract',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extract',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
