# Generated by Django 4.0.3 on 2022-03-13 11:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('saleapp', '0007_remove_extract_date_extract_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extract',
            name='updated_date',
        ),
        migrations.AlterField(
            model_name='extract',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
